### ISSUE TITLE
Unsubscribe to Lightstreamer

### ISSUE THREAD

**Issue by julienkermarec** [Lightstreamer/Lightstreamer-JMS-example-StockList-client-javascript#2]
How to Unsubscribe to Lightstreamer Subscribtion ?

**Comment by gfinocchiaro** [comment]
Could you please expand a little bit on this?

**Comment by julienkermarec** [comment]
Hello @gfinocchiaro, thank you for your reply.

I use Lightstreamer to connect with credentials with the method connectToLightstreamer() and after with subscribeToLightstreamer();

I have a problem when i want to change user or to change the subscribtion.

I don't find the logout or the unsubscribtion, how is necessary because if i try connectToLightStreamer and subscribeToLightStreamer i have this error : "Lightstreamer is not connected" (on subscribeToLightstreamer function)

**Comment by julienkermarec** [comment]
Actually, i need to restart the nodejs server to changer user and make new subscription.

**Comment by gfinocchiaro** [comment]
In this demo, there is no track of the methods you mentioned. Maybe are you referring to another Lightstreamer demo repository?

**Comment by julienkermarec** [comment]
Sorry, its the node-js-api its a mistakes !
